version: "3.8"
services:
  # Mysql database container
  db:
    image: mysql
    container_name: news_app_db
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    expose:
      - 3306
    ports:
        - "3306:3306"
    networks:
      - tutorial

  # Symfony apache project container
  www:
    build: docker/php
    container_name: news-app
    ports:
      - "8000:80"
    volumes:
      - ./docker/php/vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - tutorial

networks:
  tutorial:

volumes:
  db-data: